/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PricingIndexRouteImport } from './routes/pricing/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardBotsBotIdRouteImport } from './routes/dashboard/bots/$botId'
import { Route as DashboardBillingUsageRouteImport } from './routes/dashboard/billing/usage'
import { Route as DashboardBillingSubscriptionRouteImport } from './routes/dashboard/billing/subscription'
import { Route as AuthAuthCallbackRouteImport } from './routes/_auth/auth.callback'
import { Route as DashboardBotsBotIdWidgetRouteImport } from './routes/dashboard/bots/$botId/widget'
import { Route as DashboardBotsBotIdConfigureRouteImport } from './routes/dashboard/bots/$botId/configure'
import { Route as DashboardBotsBotIdChatRouteImport } from './routes/dashboard/bots/$botId/chat'
import { Route as DashboardBotsBotIdAnalyticsRouteImport } from './routes/dashboard/bots/$botId/analytics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBotsBotIdRoute = DashboardBotsBotIdRouteImport.update({
  id: '/dashboard/bots/$botId',
  path: '/dashboard/bots/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBillingUsageRoute = DashboardBillingUsageRouteImport.update({
  id: '/dashboard/billing/usage',
  path: '/dashboard/billing/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBillingSubscriptionRoute =
  DashboardBillingSubscriptionRouteImport.update({
    id: '/dashboard/billing/subscription',
    path: '/dashboard/billing/subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthAuthCallbackRoute = AuthAuthCallbackRouteImport.update({
  id: '/_auth/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBotsBotIdWidgetRoute =
  DashboardBotsBotIdWidgetRouteImport.update({
    id: '/widget',
    path: '/widget',
    getParentRoute: () => DashboardBotsBotIdRoute,
  } as any)
const DashboardBotsBotIdConfigureRoute =
  DashboardBotsBotIdConfigureRouteImport.update({
    id: '/configure',
    path: '/configure',
    getParentRoute: () => DashboardBotsBotIdRoute,
  } as any)
const DashboardBotsBotIdChatRoute = DashboardBotsBotIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardBotsBotIdRoute,
} as any)
const DashboardBotsBotIdAnalyticsRoute =
  DashboardBotsBotIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardBotsBotIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/auth/callback': typeof AuthAuthCallbackRoute
  '/dashboard/billing/subscription': typeof DashboardBillingSubscriptionRoute
  '/dashboard/billing/usage': typeof DashboardBillingUsageRoute
  '/dashboard/bots/$botId': typeof DashboardBotsBotIdRouteWithChildren
  '/dashboard/bots/$botId/analytics': typeof DashboardBotsBotIdAnalyticsRoute
  '/dashboard/bots/$botId/chat': typeof DashboardBotsBotIdChatRoute
  '/dashboard/bots/$botId/configure': typeof DashboardBotsBotIdConfigureRoute
  '/dashboard/bots/$botId/widget': typeof DashboardBotsBotIdWidgetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/auth/callback': typeof AuthAuthCallbackRoute
  '/dashboard/billing/subscription': typeof DashboardBillingSubscriptionRoute
  '/dashboard/billing/usage': typeof DashboardBillingUsageRoute
  '/dashboard/bots/$botId': typeof DashboardBotsBotIdRouteWithChildren
  '/dashboard/bots/$botId/analytics': typeof DashboardBotsBotIdAnalyticsRoute
  '/dashboard/bots/$botId/chat': typeof DashboardBotsBotIdChatRoute
  '/dashboard/bots/$botId/configure': typeof DashboardBotsBotIdConfigureRoute
  '/dashboard/bots/$botId/widget': typeof DashboardBotsBotIdWidgetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/_auth/auth/callback': typeof AuthAuthCallbackRoute
  '/dashboard/billing/subscription': typeof DashboardBillingSubscriptionRoute
  '/dashboard/billing/usage': typeof DashboardBillingUsageRoute
  '/dashboard/bots/$botId': typeof DashboardBotsBotIdRouteWithChildren
  '/dashboard/bots/$botId/analytics': typeof DashboardBotsBotIdAnalyticsRoute
  '/dashboard/bots/$botId/chat': typeof DashboardBotsBotIdChatRoute
  '/dashboard/bots/$botId/configure': typeof DashboardBotsBotIdConfigureRoute
  '/dashboard/bots/$botId/widget': typeof DashboardBotsBotIdWidgetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/pricing/'
    | '/auth/callback'
    | '/dashboard/billing/subscription'
    | '/dashboard/billing/usage'
    | '/dashboard/bots/$botId'
    | '/dashboard/bots/$botId/analytics'
    | '/dashboard/bots/$botId/chat'
    | '/dashboard/bots/$botId/configure'
    | '/dashboard/bots/$botId/widget'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/settings'
    | '/dashboard'
    | '/pricing'
    | '/auth/callback'
    | '/dashboard/billing/subscription'
    | '/dashboard/billing/usage'
    | '/dashboard/bots/$botId'
    | '/dashboard/bots/$botId/analytics'
    | '/dashboard/bots/$botId/chat'
    | '/dashboard/bots/$botId/configure'
    | '/dashboard/bots/$botId/widget'
  id:
    | '__root__'
    | '/'
    | '/_auth/login'
    | '/_auth/signup'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/pricing/'
    | '/_auth/auth/callback'
    | '/dashboard/billing/subscription'
    | '/dashboard/billing/usage'
    | '/dashboard/bots/$botId'
    | '/dashboard/bots/$botId/analytics'
    | '/dashboard/bots/$botId/chat'
    | '/dashboard/bots/$botId/configure'
    | '/dashboard/bots/$botId/widget'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PricingIndexRoute: typeof PricingIndexRoute
  AuthAuthCallbackRoute: typeof AuthAuthCallbackRoute
  DashboardBillingSubscriptionRoute: typeof DashboardBillingSubscriptionRoute
  DashboardBillingUsageRoute: typeof DashboardBillingUsageRoute
  DashboardBotsBotIdRoute: typeof DashboardBotsBotIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bots/$botId': {
      id: '/dashboard/bots/$botId'
      path: '/dashboard/bots/$botId'
      fullPath: '/dashboard/bots/$botId'
      preLoaderRoute: typeof DashboardBotsBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/billing/usage': {
      id: '/dashboard/billing/usage'
      path: '/dashboard/billing/usage'
      fullPath: '/dashboard/billing/usage'
      preLoaderRoute: typeof DashboardBillingUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/billing/subscription': {
      id: '/dashboard/billing/subscription'
      path: '/dashboard/billing/subscription'
      fullPath: '/dashboard/billing/subscription'
      preLoaderRoute: typeof DashboardBillingSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth/callback': {
      id: '/_auth/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bots/$botId/widget': {
      id: '/dashboard/bots/$botId/widget'
      path: '/widget'
      fullPath: '/dashboard/bots/$botId/widget'
      preLoaderRoute: typeof DashboardBotsBotIdWidgetRouteImport
      parentRoute: typeof DashboardBotsBotIdRoute
    }
    '/dashboard/bots/$botId/configure': {
      id: '/dashboard/bots/$botId/configure'
      path: '/configure'
      fullPath: '/dashboard/bots/$botId/configure'
      preLoaderRoute: typeof DashboardBotsBotIdConfigureRouteImport
      parentRoute: typeof DashboardBotsBotIdRoute
    }
    '/dashboard/bots/$botId/chat': {
      id: '/dashboard/bots/$botId/chat'
      path: '/chat'
      fullPath: '/dashboard/bots/$botId/chat'
      preLoaderRoute: typeof DashboardBotsBotIdChatRouteImport
      parentRoute: typeof DashboardBotsBotIdRoute
    }
    '/dashboard/bots/$botId/analytics': {
      id: '/dashboard/bots/$botId/analytics'
      path: '/analytics'
      fullPath: '/dashboard/bots/$botId/analytics'
      preLoaderRoute: typeof DashboardBotsBotIdAnalyticsRouteImport
      parentRoute: typeof DashboardBotsBotIdRoute
    }
  }
}

interface DashboardBotsBotIdRouteChildren {
  DashboardBotsBotIdAnalyticsRoute: typeof DashboardBotsBotIdAnalyticsRoute
  DashboardBotsBotIdChatRoute: typeof DashboardBotsBotIdChatRoute
  DashboardBotsBotIdConfigureRoute: typeof DashboardBotsBotIdConfigureRoute
  DashboardBotsBotIdWidgetRoute: typeof DashboardBotsBotIdWidgetRoute
}

const DashboardBotsBotIdRouteChildren: DashboardBotsBotIdRouteChildren = {
  DashboardBotsBotIdAnalyticsRoute: DashboardBotsBotIdAnalyticsRoute,
  DashboardBotsBotIdChatRoute: DashboardBotsBotIdChatRoute,
  DashboardBotsBotIdConfigureRoute: DashboardBotsBotIdConfigureRoute,
  DashboardBotsBotIdWidgetRoute: DashboardBotsBotIdWidgetRoute,
}

const DashboardBotsBotIdRouteWithChildren =
  DashboardBotsBotIdRoute._addFileChildren(DashboardBotsBotIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PricingIndexRoute: PricingIndexRoute,
  AuthAuthCallbackRoute: AuthAuthCallbackRoute,
  DashboardBillingSubscriptionRoute: DashboardBillingSubscriptionRoute,
  DashboardBillingUsageRoute: DashboardBillingUsageRoute,
  DashboardBotsBotIdRoute: DashboardBotsBotIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
